"use client";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import { CheckCircle2, Search, WalletCards, XCircle } from "lucide-react";
import { formatBaseQuantity, formatMoney } from "@/lib/inventory-management";
import { procurementService, type PurchaseOrderRow } from "@/services/inventory-management/procurement.service";

export function PurchaseFinanceVerificationPage() {
  const [search,setSearch]=useState(""); const [selected,setSelected]=useState<PurchaseOrderRow|null>(null); const [note,setNote]=useState("Budget availability checked and sufficient for this purchase."); const qc=useQueryClient();
  const query=useQuery({queryKey:["procurement","finance-verification",search],queryFn:()=>procurementService.purchaseOrders({search,per_page:100},"finance"),retry:false});
  const refresh=()=>{qc.invalidateQueries({queryKey:["procurement","finance-verification"]});qc.invalidateQueries({queryKey:["procurement","purchase-orders"]});};
  const verify=useMutation({mutationFn:()=>procurementService.verifyPurchaseBudget(selected!.id,note),onSuccess:()=>{toast.success("Budget verified; request sent to Manager");setSelected(null);refresh();},onError:(e:any)=>toast.error(e?.message??"Budget verification failed")});
  const reject=useMutation({mutationFn:()=>procurementService.rejectPurchaseBudget(selected!.id,note),onSuccess:()=>{toast.success("Purchase request rejected by Finance");setSelected(null);refresh();},onError:(e:any)=>toast.error(e?.message??"Budget rejection failed")});
  const rows=(query.data?.data??[]).filter(po=>["food_validated","finance_verified","finance_rejected","approved","partially_received","completed"].includes(po.status));
  return <div className="space-y-6"><Card><CardHeader><div className="flex flex-col gap-3 md:flex-row md:items-center md:justify-between"><div><CardTitle className="flex items-center gap-2"><WalletCards className="h-5 w-5"/>Purchase Budget Confirmation</CardTitle><CardDescription>Review F&amp;B validated requests and keep Finance-confirmed/rejected requests visible with their current workflow status.</CardDescription></div><div className="relative md:w-80"><Search className="absolute left-3 top-2.5 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search PO or supplier..."/></div></div></CardHeader><CardContent>{query.isLoading?<p className="text-sm text-muted-foreground">Loading...</p>:rows.length?<Table><TableHeader><TableRow><TableHead>PO</TableHead><TableHead>Supplier</TableHead><TableHead>Items</TableHead><TableHead>Total</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{rows.map(po=><TableRow key={po.id}><TableCell className="font-medium">{po.po_number??`PO-${po.id}`}</TableCell><TableCell>{po.supplier?.name??`Supplier #${po.supplier_id}`}</TableCell><TableCell>{po.items?.length??0}</TableCell><TableCell>{formatMoney(po.total??0)} ETB</TableCell><TableCell><Badge variant={po.status.includes("reject")?"destructive":"secondary"}>{po.status.replaceAll("_"," ")}</Badge></TableCell><TableCell className="text-right">{po.status==="food_validated"?<Button size="sm" onClick={()=>{setSelected(po);setNote("Budget availability checked and sufficient for this purchase.")}}>Review budget</Button>:<span className="text-sm text-muted-foreground">Processed</span>}</TableCell></TableRow>)}</TableBody></Table>:<div className="rounded-xl border border-dashed p-8 text-center">No purchase requests available for Finance.</div>}</CardContent></Card>
  <Dialog open={!!selected} onOpenChange={o=>!o&&setSelected(null)}><DialogContent className="max-w-4xl"><DialogHeader><DialogTitle>Finance purchase budget confirmation</DialogTitle><DialogDescription>Review the complete purchase detail and confirm whether sufficient budget is available.</DialogDescription></DialogHeader>{selected&&<div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><div className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">Purchase Order</div><div className="font-semibold">{selected.po_number??`PO-${selected.id}`}</div></div><div className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">Supplier</div><div className="font-semibold">{selected.supplier?.name??"—"}</div></div><div className="rounded-lg border p-3"><div className="text-xs text-muted-foreground">Requested Total</div><div className="font-semibold">{formatMoney(selected.total??0)} ETB</div></div></div><div className="max-h-72 overflow-auto rounded-lg border"><Table><TableHeader><TableRow><TableHead>Item</TableHead><TableHead>Qty</TableHead><TableHead>Unit Cost</TableHead><TableHead>Total</TableHead></TableRow></TableHeader><TableBody>{(selected.items??[]).map(i=>{const inv=i.inventory_item??i.inventoryItem; const unit=inv?.base_unit??i.unit??"pcs";return <TableRow key={i.id}><TableCell>{inv?.name??`Item #${i.inventory_item_id}`}</TableCell><TableCell>{formatBaseQuantity(i.quantity,unit)}</TableCell><TableCell>{formatMoney(i.unit_cost)} ETB</TableCell><TableCell>{formatMoney(i.line_total??Number(i.quantity)*Number(i.unit_cost))} ETB</TableCell></TableRow>})}</TableBody></Table></div><div><Label>Finance note / rejection reason</Label><Textarea className="mt-2" value={note} onChange={e=>setNote(e.target.value)}/></div></div>}<DialogFooter><Button variant="outline" onClick={()=>setSelected(null)}>Cancel</Button><Button variant="destructive" disabled={!note.trim()||reject.isPending||verify.isPending} onClick={()=>reject.mutate()}><XCircle className="mr-2 h-4 w-4"/>Budget not sufficient</Button><Button disabled={verify.isPending||reject.isPending} onClick={()=>verify.mutate()}><CheckCircle2 className="mr-2 h-4 w-4"/>Verify budget sufficient</Button></DialogFooter></DialogContent></Dialog></div>;
}
