"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { Textarea } from "@/components/ui/textarea";
import inventoryService from "@/services/inventory-management/inventory.service";
import { formatBaseQuantity } from "@/lib/inventory-management";

export function StockoutRequestQueuePage({ mode }: { mode: "validation" | "issue" }) {
  const client=useQueryClient(), [status,setStatus]=useState(mode==="validation"?"submitted":"validated"), [rejectRow,setRejectRow]=useState<any>(null), [note,setNote]=useState("");
  const scope=mode==="validation"?"food-controller":"stock-keeper";
  const query=useQuery({queryKey:["stockout-requests",scope,status],queryFn:()=>inventoryService.stockoutRequestQueue(scope,status)});
  const action=useMutation({mutationFn:({row,type}:{row:any;type:"validate"|"reject"|"issue"})=>type==="validate"?inventoryService.validateStockoutRequest(row.id):type==="reject"?inventoryService.rejectStockoutRequest(row.id,note.trim()):inventoryService.issueStockoutRequest(row.id),onSuccess:(response:any)=>{toast.success(response?.message??"Request updated");setRejectRow(null);setNote("");client.invalidateQueries({queryKey:["stockout-requests"]});client.invalidateQueries({queryKey:["inventory"]});},onError:(error)=>toast.error(error instanceof Error?error.message:"Action failed")});
  const rows=query.data?.data??[];
  return <div className="space-y-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">{mode==="validation"?"Stock-out Request Validation":"Validated Stock-out Requests"}</h1><p className="text-sm text-muted-foreground">{mode==="validation"?"Validate department requests before the Store Keeper issues stock.":"Accept validated requests and issue stock to the requesting responsible user."}</p></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-48"><SelectValue/></SelectTrigger><SelectContent>{(mode==="validation"?["submitted","validated","rejected","issued","all"]:["validated","issued","all"]).map(value=><SelectItem key={value} value={value}>{value.replace(/^./,c=>c.toUpperCase())}</SelectItem>)}</SelectContent></Select></div>
  <div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Request</TableHead><TableHead>Department</TableHead><TableHead>Requested by</TableHead><TableHead>Item</TableHead><TableHead>Quantity</TableHead><TableHead>Reason</TableHead><TableHead>Status</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{query.isLoading?<TableRow><TableCell colSpan={8} className="py-10 text-center">Loading requests...</TableCell></TableRow>:rows.length?rows.map((row:any)=><TableRow key={row.id}><TableCell className="font-medium">{row.request_number}</TableCell><TableCell>{row.department?.name??"—"}</TableCell><TableCell>{row.requester?.name??"—"}</TableCell><TableCell>{row.inventory_item?.name??row.inventoryItem?.name??"—"}</TableCell><TableCell>{formatBaseQuantity(row.quantity,row.inventory_item?.base_unit??row.inventoryItem?.base_unit??"pcs")}</TableCell><TableCell className="max-w-64 whitespace-normal">{row.reason}</TableCell><TableCell><Badge variant="secondary">{row.status}</Badge></TableCell><TableCell><div className="flex justify-end gap-2">{mode==="validation"&&row.status==="submitted"&&<><Button size="sm" onClick={()=>action.mutate({row,type:"validate"})}>Validate</Button><Button size="sm" variant="destructive" onClick={()=>setRejectRow(row)}>Reject</Button></>}{mode==="issue"&&row.status==="validated"&&<Button size="sm" onClick={()=>action.mutate({row,type:"issue"})}>Accept & issue</Button>}{!["submitted","validated"].includes(row.status)&&<span className="text-sm text-muted-foreground">Completed</span>}</div></TableCell></TableRow>):<TableRow><TableCell colSpan={8} className="py-10 text-center text-muted-foreground">No requests found.</TableCell></TableRow>}</TableBody></Table></div>
  <Dialog open={!!rejectRow} onOpenChange={open=>!open&&setRejectRow(null)}><DialogContent><DialogHeader><DialogTitle>Reject stock-out request</DialogTitle></DialogHeader><Textarea value={note} onChange={event=>setNote(event.target.value)} placeholder="Mandatory rejection reason"/><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setRejectRow(null)}>Cancel</Button><Button variant="destructive" disabled={!note.trim()||action.isPending} onClick={()=>rejectRow&&action.mutate({row:rejectRow,type:"reject"})}>Reject request</Button></div></DialogContent></Dialog></div>;
}
