"use client";

import { useQuery } from "@tanstack/react-query";
import type { ReactNode } from "react";
import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import api, { unwrap } from "@/lib/api";

type N=number|null;
type Report={report_date:string;sales_performance:any[];food_beverage_cost:Record<string,N>;prime_cost:Record<string,N>;inventory:Record<string,N>;procurement:Record<string,N>;credit_ar:Record<string,N>;pnl:Record<string,N>;cash_position:Record<string,N>;exceptions:any[]};
export type ManagerReportKind="sales"|"food-beverage"|"prime-cost"|"inventory-variance"|"procurement"|"credit-ar"|"pnl"|"cash-position"|"exceptions";
const money=(v:N)=>v==null?"—":`ETB ${new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v)}`;
const value=(v:N)=>v==null?"—":new Intl.NumberFormat("en-US",{maximumFractionDigits:2}).format(v);
const pct=(v:N)=>v==null?"—":`${Number(v).toFixed(1)}%`;
const titles:Record<ManagerReportKind,string>={sales:"Sales Performance", "food-beverage":"Food & Beverage Cost", "prime-cost":"Prime Cost", "inventory-variance":"Inventory Variance", procurement:"Procurement Summary", "credit-ar":"Credit / AR Summary", pnl:"P&L Summary", "cash-position":"Cash Position", exceptions:"Exception Reports"};
function Card({children}:{children:ReactNode}){return <div className="rounded-xl border bg-card p-5 shadow-sm">{children}</div>}
function Metric({label,v}:{label:string;v:string}){return <Card><div className="text-xs font-medium text-muted-foreground">{label}</div><div className="mt-2 text-2xl font-bold">{v}</div></Card>}
function Table({headers,rows}:{headers:string[];rows:(string|number)[][]}){return <div className="overflow-x-auto rounded-xl border"><table className="w-full text-sm"><thead className="bg-muted/60"><tr>{headers.map(h=><th key={h} className="px-4 py-3 text-left font-semibold">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t">{r.map((c,j)=><td key={j} className="px-4 py-3">{c}</td>)}</tr>)}</tbody></table></div>}
export default function ManagementReportPage({kind}:{kind:ManagerReportKind}){
 const q=useQuery({queryKey:["manager-management-report",kind],queryFn:async()=>unwrap<{data:Report}>(await api.get("/manager/dashboard")).data,refetchInterval:60000});
 if(q.isLoading)return <div className="p-6">Loading report…</div>; if(q.isError||!q.data)return <div className="p-6 text-destructive">Unable to load report.</div>; const d=q.data;
 return <div className="space-y-5 p-4 md:p-6"><div><h1 className="text-2xl font-bold">{titles[kind]}</h1><p className="text-sm text-muted-foreground">Management report · {d.report_date} · live operational data</p></div><ReportBody kind={kind} d={d}/></div>
}
function ReportBody({kind,d}:{kind:ManagerReportKind;d:Report}){
 if(kind==="sales"){const total=d.sales_performance.reduce((s,x)=>s+Number(x.sales||0),0),covers=d.sales_performance.reduce((s,x)=>s+Number(x.covers||0),0);return <><div className="grid gap-3 md:grid-cols-3"><Metric label="7-day Sales" v={money(total)}/><Metric label="7-day Covers" v={value(covers)}/><Metric label="Average Check" v={money(covers?total/covers:0)}/></div><Card><div className="h-80"><ResponsiveContainer width="100%" height="100%"><LineChart data={d.sales_performance}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="label"/><YAxis/><Tooltip/><Line dataKey="sales" name="Sales" stroke="currentColor"/><Line dataKey="sales_ly" name="Last year" stroke="currentColor" strokeDasharray="5 5"/></LineChart></ResponsiveContainer></div></Card><Table headers={["Date","Period","Sales","Last Year","Covers"]} rows={d.sales_performance.map(x=>[x.date,x.label,money(x.sales),money(x.sales_ly),x.covers])}/></>}
 if(kind==="food-beverage"){const x=d.food_beverage_cost;const chart=[{name:"Food",cost:x.food_cost||0,pct:x.food_cost_pct||0},{name:"Beverage",cost:x.beverage_cost||0,pct:x.beverage_cost_pct||0}];return <><div className="grid gap-3 md:grid-cols-4"><Metric label="Food Cost" v={money(x.food_cost)}/><Metric label="Food Cost %" v={pct(x.food_cost_pct)}/><Metric label="Beverage Cost" v={money(x.beverage_cost)}/><Metric label="Beverage Cost %" v={pct(x.beverage_cost_pct)}/></div><Card><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="cost" name="Cost" fill="currentColor"/></BarChart></ResponsiveContainer></div></Card><Table headers={["Cost Type","Amount","Cost %"]} rows={chart.map(x=>[x.name,money(x.cost),pct(x.pct)])}/></>}
 if(kind==="prime-cost"){const x=d.prime_cost;const rows=[["Food Cost",x.food_cost],["Beverage Cost",x.beverage_cost],["Labor Cost",x.labor_cost],["Other Cost",x.other_cost]] as [string,N][];return <><div className="grid gap-3 md:grid-cols-2"><Metric label="Prime Cost" v={money(x.prime_cost)}/><Metric label="Prime Cost %" v={pct(x.prime_cost_pct)}/></div><Card><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={rows.map(([name,cost])=>({name,cost:cost||0}))}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="cost" fill="currentColor"/></BarChart></ResponsiveContainer></div></Card><Table headers={["Component","Amount"]} rows={rows.map(([a,b])=>[a,money(b)])}/></>}
 if(kind==="inventory-variance"){const x=d.inventory;return <><div className="grid gap-3 md:grid-cols-4"><Metric label="Stock Value" v={money(x.stock_value)}/><Metric label="Today's Consumption" v={money(x.today_consumption)}/><Metric label="Low Stock" v={value(x.low_stock)}/><Metric label="Out of Stock" v={value(x.out_of_stock)}/></div><Table headers={["Measure","Value"]} rows={[["Stock Value",money(x.stock_value)],["Today's Consumption",money(x.today_consumption)],["Low Stock Items",value(x.low_stock)],["Out of Stock Items",value(x.out_of_stock)],["Book vs Actual Variance",money(x.book_vs_actual_variance)]]}/></>}
 if(kind==="procurement"){const x=d.procurement;const chart=[{name:"POs",v:x.number_of_pos||0},{name:"Pending",v:x.pending_approval||0},{name:"Open",v:x.open_po||0},{name:"Awaiting Delivery",v:x.awaiting_delivery||0}];return <><div className="grid gap-3 md:grid-cols-3"><Metric label="Total Purchases" v={money(x.total_purchases)}/><Metric label="Number of POs" v={value(x.number_of_pos)}/><Metric label="Price Variance" v={pct(x.price_variance_pct)}/></div><Card><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="v" fill="currentColor"/></BarChart></ResponsiveContainer></div></Card><Table headers={["Measure","Value"]} rows={chart.map(x=>[x.name,x.v])}/></>}
 if(kind==="credit-ar"){const x=d.credit_ar;const chart=[{name:"0–30",v:x.current||0},{name:"31–60",v:x.days_31_60||0},{name:"61–90",v:x.days_61_90||0},{name:">90",v:x.over_90||0}];return <><Metric label="Total Accounts Receivable" v={money(x.total_ar)}/><Card><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={chart}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="v" fill="currentColor"/></BarChart></ResponsiveContainer></div></Card><Table headers={["Age Bucket","Outstanding Amount"]} rows={chart.map(x=>[x.name,money(x.v)])}/></>}
 if(kind==="pnl"){const x=d.pnl;return <><div className="grid gap-3 md:grid-cols-3"><Metric label="Net Revenue" v={money(x.net_revenue)}/><Metric label="Gross Profit" v={money(x.gross_profit)}/><Metric label="Net Profit" v={money(x.net_profit)}/></div><Table headers={["P&L Line","Actual"]} rows={[["Total Revenue",money(x.total_revenue)],["Refunds",money(x.refunds)],["Net Revenue",money(x.net_revenue)],["Cost of Sales",money(x.cost_of_sales)],["Gross Profit",money(x.gross_profit)],["Operating Expenses",money(x.operating_expenses)],["Net Profit",money(x.net_profit)]]}/></>}
 if(kind==="cash-position"){const x=d.cash_position;return <><div className="grid gap-3 md:grid-cols-3"><Metric label="Closing Cash" v={money(x.closing_cash)}/><Metric label="Expected POS" v={money(x.expected_pos)}/><Metric label="Variance" v={money(x.variance)}/></div><Table headers={["Cash Measure","Amount"]} rows={[["Opening Cash",money(x.opening_cash)],["Cash Received",money(x.cash_received)],["Cash Paid Out",money(x.cash_paid_out)],["Closing Cash",money(x.closing_cash)],["Expected POS",money(x.expected_pos)],["Variance",money(x.variance)]]}/></>}
 return <><div className="grid gap-3 md:grid-cols-2"><Metric label="Open Exceptions" v={value(d.exceptions.length)}/><Metric label="Financial Impact" v={money(d.exceptions.reduce((s,x)=>s+Number(x.impact||0),0))}/></div><Table headers={["Area","Issue","Impact","Required Action"]} rows={d.exceptions.length?d.exceptions.map(x=>[x.area,x.issue,money(x.impact),x.action]):[["—","No current exceptions requiring manager action","—","—"]]}/></>;
}
