"use client";

import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import api, { unwrap } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";

const money=(value:unknown)=>`${Number(value??0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} ETB`;

export function ProfitExpensePage(){
  const client=useQueryClient(), [from,setFrom]=useState(""), [to,setTo]=useState(""), [open,setOpen]=useState(false);
  const [form,setForm]=useState({category:"",description:"",amount:"",expense_date:new Date().toISOString().slice(0,10),reference:""}), [file,setFile]=useState<File|null>(null);
  const filters={date_from:from||undefined,date_to:to||undefined};
  const profit=useQuery({queryKey:["finance","profit",filters],queryFn:async()=>unwrap<any>(await api.get("/finance/reports/profit",{params:filters}))});
  const expenses=useQuery({queryKey:["finance","expenses",filters],queryFn:async()=>unwrap<any>(await api.get("/finance/expenses",{params:{...filters,per_page:100}}))});
  const create=useMutation({mutationFn:async()=>{const body=new FormData();Object.entries(form).forEach(([key,value])=>body.append(key,value));if(file)body.append("attachment",file);return unwrap<any>(await api.post("/finance/expenses",body,{headers:{"Content-Type":"multipart/form-data"}}));},onSuccess:()=>{toast.success("Expense recorded");setOpen(false);setFile(null);setForm({category:"",description:"",amount:"",expense_date:new Date().toISOString().slice(0,10),reference:""});client.invalidateQueries({queryKey:["finance","expenses"]});client.invalidateQueries({queryKey:["finance","profit"]});},onError:(error)=>toast.error(error instanceof Error?error.message:"Could not record expense")});
  const remove=useMutation({mutationFn:async(id:number|string)=>unwrap(await api.delete(`/finance/expenses/${id}`)),onSuccess:()=>{toast.success("Expense deleted");client.invalidateQueries({queryKey:["finance","expenses"]});client.invalidateQueries({queryKey:["finance","profit"]});}});
  const summary=profit.data?.data??profit.data??{}, rows=expenses.data?.data??[];
  return <div className="space-y-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-2xl font-bold">Profit & Expenses</h1><p className="text-sm text-muted-foreground">Revenue less approved consumption cost, processed refunds, and Finance-recorded expenses.</p></div><Button onClick={()=>setOpen(true)}>Record expense</Button></div>
  <section className="grid gap-4 rounded-xl border bg-card p-4 md:grid-cols-3"><div><Label>From date</Label><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></div><div><Label>To date</Label><Input type="date" min={from||undefined} value={to} onChange={e=>setTo(e.target.value)}/></div><div className="flex items-end"><Button variant="outline" className="w-full" onClick={()=>{profit.refetch();expenses.refetch()}}>Refresh report</Button></div></section>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Card><CardHeader><CardTitle className="text-sm">Net Revenue</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{money(summary.net_revenue)}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Approved Consumption</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{money(summary.approved_consumption_cost)}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Other Expenses</CardTitle></CardHeader><CardContent className="text-2xl font-bold">{money(summary.other_expenses)}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Net Profit</CardTitle></CardHeader><CardContent className={`text-2xl font-bold ${Number(summary.net_profit)<0?"text-destructive":"text-emerald-700"}`}>{money(summary.net_profit)}<div className="text-xs font-normal text-muted-foreground">Margin {Number(summary.profit_margin??0).toFixed(2)}%</div></CardContent></Card></div>
  <div className="grid gap-4 sm:grid-cols-3"><Card><CardHeader><CardTitle className="text-sm">Gross Revenue</CardTitle></CardHeader><CardContent>{money(summary.gross_revenue)}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Processed Refunds</CardTitle></CardHeader><CardContent>{money(summary.refunds)}</CardContent></Card><Card><CardHeader><CardTitle className="text-sm">Total Expenses</CardTitle></CardHeader><CardContent>{money(summary.total_expenses)}</CardContent></Card></div>
  <div className="overflow-x-auto rounded-xl border bg-card"><Table><TableHeader><TableRow><TableHead>Expense</TableHead><TableHead>Date</TableHead><TableHead>Category</TableHead><TableHead>Description</TableHead><TableHead>Reference</TableHead><TableHead>Amount</TableHead><TableHead>Recorded by</TableHead><TableHead className="text-right">Action</TableHead></TableRow></TableHeader><TableBody>{rows.length?rows.map((row:any)=><TableRow key={row.id}><TableCell>{row.expense_number}</TableCell><TableCell>{row.expense_date?new Date(row.expense_date).toLocaleDateString():"—"}</TableCell><TableCell>{row.category}</TableCell><TableCell>{row.description}</TableCell><TableCell>{row.reference??"—"}</TableCell><TableCell>{money(row.amount)}</TableCell><TableCell>{row.recorder?.name??"—"}</TableCell><TableCell className="text-right"><Button size="sm" variant="destructive" disabled={remove.isPending} onClick={()=>remove.mutate(row.id)}>Delete</Button></TableCell></TableRow>):<TableRow><TableCell colSpan={8} className="py-10 text-center text-muted-foreground">No expenses found.</TableCell></TableRow>}</TableBody></Table></div>
  <Dialog open={open} onOpenChange={setOpen}><DialogContent><DialogHeader><DialogTitle>Record operating expense</DialogTitle></DialogHeader><div className="space-y-3"><div><Label>Category *</Label><Input value={form.category} onChange={e=>setForm({...form,category:e.target.value})} placeholder="Utilities, maintenance, transport..."/></div><div><Label>Description *</Label><Textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></div><div className="grid gap-3 sm:grid-cols-2"><div><Label>Amount *</Label><Input type="number" min="0.01" step="0.01" value={form.amount} onChange={e=>setForm({...form,amount:e.target.value})}/></div><div><Label>Expense date *</Label><Input type="date" value={form.expense_date} onChange={e=>setForm({...form,expense_date:e.target.value})}/></div></div><div><Label>Reference</Label><Input value={form.reference} onChange={e=>setForm({...form,reference:e.target.value})}/></div><div><Label>Attachment</Label><Input type="file" accept=".jpg,.jpeg,.png,.pdf" onChange={e=>setFile(e.target.files?.[0]??null)}/></div><div className="flex justify-end gap-2"><Button variant="outline" onClick={()=>setOpen(false)}>Cancel</Button><Button disabled={!form.category.trim()||!form.description.trim()||Number(form.amount)<=0||!form.expense_date||create.isPending} onClick={()=>create.mutate()}>Save expense</Button></div></div></DialogContent></Dialog></div>;
}
