import api from "@/lib/api";
const unwrap=<T,>(r:any):T=>r?.data?.data ?? r?.data ?? r;
export const accountingEngineService={
 integrationSettings:async()=>unwrap<any>(await api.get("/finance/accounting/integration-settings")),
 saveIntegrationSettings:async(payload:any)=>unwrap<any>(await api.put("/finance/accounting/integration-settings",payload)),
 autoPostingSummary:async()=>unwrap<any>(await api.get("/finance/accounting/auto-posting-summary")),
 inventoryMappings:async()=>unwrap<any[]>(await api.get("/finance/accounting/inventory-mappings")),
 updateInventoryMapping:async(id:number,payload:any)=>unwrap<any>(await api.put(`/finance/accounting/inventory-mappings/${id}`,payload)),
 inventoryPostingSummary:async()=>unwrap<any>(await api.get("/finance/accounting/inventory-posting-summary")),
 supplierPayables:async()=>unwrap<any>(await api.get("/finance/accounting/supplier-payables")),
 createSupplierPayment:async(payload:any)=>unwrap<any>(await api.post("/finance/accounting/supplier-payments",payload)),
 procurementSummary:async()=>unwrap<any>(await api.get("/finance/accounting/procurement-summary")),
 accountsReceivable:async()=>unwrap<any>(await api.get("/finance/accounting/accounts-receivable")),
 cashBank:async()=>unwrap<any>(await api.get("/finance/accounting/cash-bank")),
 createCashBankTransfer:async(payload:any)=>unwrap<any>(await api.post("/finance/accounting/cash-bank/transfers",payload)),
 createReconciliation:async(payload:any)=>unwrap<any>(await api.post("/finance/accounting/cash-bank/reconciliations",payload)),
 fixedAssets:async()=>unwrap<any>(await api.get("/finance/accounting/fixed-assets")),
 createFixedAsset:async(payload:any)=>unwrap<any>(await api.post("/finance/accounting/fixed-assets",payload)),
 depreciateAsset:async(id:number,payload:any)=>unwrap<any>(await api.post(`/finance/accounting/fixed-assets/${id}/depreciate`,payload)),
 disposeAsset:async(id:number,payload:any)=>unwrap<any>(await api.post(`/finance/accounting/fixed-assets/${id}/dispose`,payload)),
 vatSummary:async(params:any)=>unwrap<any>(await api.get("/finance/accounting/vat-summary",{params})),
 settleVat:async(payload:any)=>unwrap<any>(await api.post("/finance/accounting/vat-settlements",payload)),
 mappings:async()=>unwrap<any[]>(await api.get("/finance/accounting/mappings")),
 updateMapping:async(id:number,payload:any)=>unwrap(await api.put(`/finance/accounting/mappings/${id}`,payload)),
 journals:async(params:any={})=>unwrap<any>(await api.get("/finance/accounting/journals",{params})),
 journal:async(id:number)=>unwrap<any>(await api.get(`/finance/accounting/journals/${id}`)),
 createJournal:async(payload:any)=>unwrap<any>(await api.post("/finance/accounting/journals",payload)),
 postJournal:async(id:number)=>unwrap<any>(await api.post(`/finance/accounting/journals/${id}/post`)),
 reverseJournal:async(id:number,payload:any)=>unwrap<any>(await api.post(`/finance/accounting/journals/${id}/reverse`,payload)),
 ledger:async(params:any)=>unwrap<any[]>(await api.get("/finance/accounting/general-ledger",{params})),
};
