"use client";

import {FormEvent,useEffect,useMemo,useState} from "react";
import {useMutation,useQuery,useQueryClient} from "@tanstack/react-query";
import {ChevronLeft,ChevronRight,Globe2,Pencil,Plus,RefreshCcw,Save,Search,X} from "lucide-react";
import {toast} from "sonner";
import api from "@/lib/api";
import {englishSourceKeys} from "@/lib/i18n/source-keys";
import {translateUiText} from "@/lib/i18n/translations";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardHeader,CardTitle,CardDescription} from "@/components/ui/card";
import {Input} from "@/components/ui/input";
import {Label} from "@/components/ui/label";
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from "@/components/ui/table";

type Lang={id:number;code:string;name:string;native_name:string;is_default:boolean;is_active:boolean;translations_count:number};
type Tr={id:number;language_id:number;translation_key:string;translation_value:string;module:string;language?:Lang};
type Row={source:string;module:string;values:Record<string,string>};

const PAGE_SIZE=50;

export default function LanguageManagement(){
 const qc=useQueryClient();
 const [search,setSearch]=useState(""); const [moduleFilter,setModuleFilter]=useState("all"); const [statusFilter,setStatusFilter]=useState("all"); const [page,setPage]=useState(1);
 const [code,setCode]=useState(""); const [name,setName]=useState(""); const [native,setNative]=useState("");
 const [editing,setEditing]=useState<Row|null>(null); const [draft,setDraft]=useState<Record<string,string>>({});
 const q=useQuery({queryKey:["admin-languages-all"],queryFn:async()=>{const r=await api.get('/admin/languages',{params:{per_page:5000}});return r.data.data as {languages:Lang[];translations:{data:Tr[]}}}});
 const refresh=()=>qc.invalidateQueries({queryKey:["admin-languages-all"]});
 const add=useMutation({mutationFn:()=>api.post('/admin/languages',{code,name,native_name:native,is_active:true}),onSuccess:()=>{toast.success('Language created');setCode('');setName('');setNative('');refresh()},onError:()=>toast.error('Could not create language')});
 const toggle=useMutation({mutationFn:(l:Lang)=>api.put(`/admin/languages/${l.id}`,{is_active:!l.is_active}),onSuccess:refresh,onError:()=>toast.error('Could not update language')});
 const makeDefault=useMutation({mutationFn:(l:Lang)=>api.put(`/admin/languages/${l.id}`,{is_default:true,is_active:true}),onSuccess:refresh});
 const sync=useMutation({mutationFn:()=>api.post('/admin/translations/sync-english-sources',{sources:englishSourceKeys.map(x=>({source:x.source,module:x.module,translations:{en:x.source,om:translateUiText("om",x.source),am:translateUiText("am",x.source)}}))}),onSuccess:(r)=>{toast.success(`Synced ${r.data?.data?.source_count??englishSourceKeys.length} English stable keys`);refresh()},onError:()=>toast.error('Could not sync stable keys')});
 const saveAll=useMutation({mutationFn:async()=>{if(!editing)return; const langs=q.data?.languages??[]; const active=langs.filter(l=>l.is_active||['en','om','am'].includes(l.code)); const translations:Object=Object.fromEntries(active.map(l=>[l.code,(draft[l.code]??'').trim()||editing.source])); return api.post('/admin/translations/grouped',{stable_key:editing.source,module:editing.module,translations});},onSuccess:async()=>{toast.success('All translations saved');setEditing(null);await qc.invalidateQueries({queryKey:['admin-languages-all']});await qc.refetchQueries({queryKey:['admin-languages-all'],type:'active'});},onError:(error:any)=>toast.error(error?.response?.data?.message||'Could not save translations')});

 const rows=useMemo<Row[]>(()=>{const trs=q.data?.translations?.data??[]; const byKey=new Map<string,Row>(); englishSourceKeys.forEach(k=>byKey.set(k.source,{source:k.source,module:k.module,values:{}})); trs.forEach(t=>{const row=byKey.get(t.translation_key); if(!row)return; if(t.language?.code)row.values[t.language.code]=t.translation_value; byKey.set(t.translation_key,row)}); return Array.from(byKey.values()).sort((a,b)=>a.source.localeCompare(b.source));},[q.data]);
 const modules=useMemo(()=>Array.from(new Set(rows.map(r=>r.module))).sort(),[rows]);
 const langCodes=['en','om','am'];
 const complete=(r:Row)=>langCodes.every(c=>(r.values[c]??(c==='en'?r.source:'')).trim().length>0);
 const filtered=useMemo(()=>rows.filter(r=>{const s=search.trim().toLowerCase(); const matchesSearch=!s||r.source.toLowerCase().includes(s)||Object.values(r.values).some(v=>v.toLowerCase().includes(s)); const matchesModule=moduleFilter==='all'||r.module===moduleFilter; const done=complete(r); const matchesStatus=statusFilter==='all'||(statusFilter==='complete'&&done)||(statusFilter==='missing'&&!done); return matchesSearch&&matchesModule&&matchesStatus;}),[rows,search,moduleFilter,statusFilter]);
 const totalPages=Math.max(1,Math.ceil(filtered.length/PAGE_SIZE)); useEffect(()=>setPage(1),[search,moduleFilter,statusFilter]); useEffect(()=>{if(page>totalPages)setPage(totalPages)},[page,totalPages]);
 const shown=filtered.slice((page-1)*PAGE_SIZE,page*PAGE_SIZE); const completeCount=rows.filter(complete).length; const missingOm=rows.filter(r=>!(r.values.om??'').trim()).length; const missingAm=rows.filter(r=>!(r.values.am??'').trim()).length;
 const openEdit=(r:Row)=>{setEditing(r);setDraft({en:r.values.en||r.source,om:r.values.om||translateUiText('om',r.source)||'',am:r.values.am||translateUiText('am',r.source)||''})};

 return <div className="space-y-6">
  <header className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><h1 className="flex items-center gap-2 text-2xl font-bold"><Globe2/>Language Management</h1><p className="text-sm text-muted-foreground">See every stable English source and edit English, Afaan Oromoo and Amharic together.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={sync.isPending} onClick={()=>sync.mutate()}><RefreshCcw className="mr-2 h-4 w-4"/>{sync.isPending?'Syncing…':`Sync All Stable Keys (${englishSourceKeys.length})`}</Button><Button variant="outline" onClick={()=>q.refetch()}><RefreshCcw className="mr-2 h-4 w-4"/>Refresh</Button></div></header>
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[["All Stable Keys",rows.length],["Fully Translated",completeCount],["Missing Afaan Oromoo",missingOm],["Missing Amharic",missingAm]].map(([a,b])=><Card key={String(a)}><CardContent className="p-5"><div className="text-sm text-muted-foreground">{a}</div><div className="mt-1 text-3xl font-bold">{b}</div></CardContent></Card>)}</div>
  <div className="grid gap-5 xl:grid-cols-[360px_1fr]"><Card><CardHeader><CardTitle>Add Language</CardTitle><CardDescription>Add another language without changing source code.</CardDescription></CardHeader><CardContent><form className="space-y-3" onSubmit={(e:FormEvent)=>{e.preventDefault();add.mutate()}}><Label>Code</Label><Input value={code} onChange={e=>setCode(e.target.value)} placeholder="e.g. so"/><Label>Name</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Somali"/><Label>Native name</Label><Input value={native} onChange={e=>setNative(e.target.value)} placeholder="Soomaali"/><Button disabled={!code||!name||!native}><Plus className="mr-2 h-4 w-4"/>Add Language</Button></form></CardContent></Card>
  <Card><CardHeader><CardTitle>Languages</CardTitle></CardHeader><CardContent><Table><TableHeader><TableRow><TableHead>Code</TableHead><TableHead>Language</TableHead><TableHead>Status</TableHead><TableHead>Actions</TableHead></TableRow></TableHeader><TableBody>{(q.data?.languages??[]).map(l=><TableRow key={l.id}><TableCell>{l.code}</TableCell><TableCell>{l.native_name}<div className="text-xs text-muted-foreground">{l.name}</div></TableCell><TableCell>{l.is_default?'Default':l.is_active?'Active':'Disabled'}</TableCell><TableCell className="space-x-2"><Button size="sm" variant="outline" disabled={l.is_default} onClick={()=>toggle.mutate(l)}>{l.is_active?'Disable':'Enable'}</Button><Button size="sm" disabled={l.is_default} onClick={()=>makeDefault.mutate(l)}>Set Default</Button></TableCell></TableRow>)}</TableBody></Table></CardContent></Card></div>
  <Card><CardHeader><CardTitle>All Stable Keys</CardTitle><CardDescription>The stable source is read-only. Edit all three translations in one popup and save once.</CardDescription></CardHeader><CardContent className="space-y-4">
   <div className="grid gap-3 lg:grid-cols-[1fr_220px_220px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-muted-foreground"/><Input className="pl-9" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search stable key or translation..."/></div><select className="h-10 rounded-md border bg-background px-3" value={moduleFilter} onChange={e=>setModuleFilter(e.target.value)}><option value="all">All modules</option>{modules.map(m=><option key={m}>{m}</option>)}</select><select className="h-10 rounded-md border bg-background px-3" value={statusFilter} onChange={e=>setStatusFilter(e.target.value)}><option value="all">All status</option><option value="complete">Complete</option><option value="missing">Missing translation</option></select></div>
   <div className="overflow-x-auto rounded-md border"><Table className="table-fixed min-w-[1180px]"><TableHeader><TableRow><TableHead className="w-[110px]">Module</TableHead><TableHead className="w-[300px]">Stable Key</TableHead><TableHead className="w-[250px]">English</TableHead><TableHead className="w-[210px]">Afaan Oromoo</TableHead><TableHead className="w-[190px]">Amharic</TableHead><TableHead className="w-[100px]">Status</TableHead><TableHead className="w-[100px] text-right">Action</TableHead></TableRow></TableHeader><TableBody>{shown.map(r=><TableRow key={r.source} className="align-top"><TableCell className="whitespace-normal break-words capitalize">{r.module}</TableCell><TableCell className="whitespace-normal break-words [overflow-wrap:anywhere] font-mono text-xs leading-5">{r.source}</TableCell><TableCell className="whitespace-normal break-words [overflow-wrap:anywhere] leading-5">{r.values.en||r.source}</TableCell><TableCell className="whitespace-normal break-words [overflow-wrap:anywhere] leading-5">{r.values.om||<span className="text-amber-600">Missing</span>}</TableCell><TableCell className="whitespace-normal break-words [overflow-wrap:anywhere] leading-5">{r.values.am||<span className="text-amber-600">Missing</span>}</TableCell><TableCell className="whitespace-normal">{complete(r)?<span className="text-emerald-600">Complete</span>:<span className="text-amber-600">Missing</span>}</TableCell><TableCell className="whitespace-nowrap text-right"><Button size="sm" variant="outline" onClick={()=>openEdit(r)}><Pencil className="mr-2 h-4 w-4"/>Edit</Button></TableCell></TableRow>)}{!shown.length&&<TableRow><TableCell colSpan={7} className="py-10 text-center text-muted-foreground">No stable keys match the current filters.</TableCell></TableRow>}</TableBody></Table></div>
   <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between"><div className="text-sm text-muted-foreground">Showing {filtered.length?((page-1)*PAGE_SIZE)+1:0}–{Math.min(page*PAGE_SIZE,filtered.length)} of {filtered.length} stable keys</div><div className="flex items-center gap-2"><Button size="sm" variant="outline" disabled={page<=1} onClick={()=>setPage(p=>p-1)}><ChevronLeft className="h-4 w-4"/>Previous</Button><span className="text-sm">Page {page} / {totalPages}</span><Button size="sm" variant="outline" disabled={page>=totalPages} onClick={()=>setPage(p=>p+1)}>Next<ChevronRight className="h-4 w-4"/></Button></div></div>
  </CardContent></Card>
  {editing&&<div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-2xl rounded-xl bg-background shadow-2xl"><div className="flex items-center justify-between border-b p-5"><div><h2 className="text-xl font-bold">Edit Translation</h2><p className="text-sm text-muted-foreground">Edit English, Afaan Oromoo and Amharic together.</p></div><Button size="icon" variant="ghost" onClick={()=>setEditing(null)}><X className="h-5 w-5"/></Button></div><div className="space-y-4 p-5"><div><Label>Stable Key / Existing English Source</Label><Input className="mt-1 font-mono" value={editing.source} readOnly disabled/><p className="mt-1 text-xs text-muted-foreground">This key is permanent and cannot be edited.</p></div><div><Label>English</Label><Input className="mt-1" value={draft.en??''} onChange={e=>setDraft(d=>({...d,en:e.target.value}))}/></div><div><Label>Afaan Oromoo</Label><Input className="mt-1" value={draft.om??''} onChange={e=>setDraft(d=>({...d,om:e.target.value}))}/></div><div><Label>Amharic</Label><Input className="mt-1" value={draft.am??''} onChange={e=>setDraft(d=>({...d,am:e.target.value}))}/></div><div className="text-xs text-muted-foreground">Module: <span className="font-medium">{editing.module}</span></div></div><div className="flex justify-end gap-2 border-t p-5"><Button variant="outline" onClick={()=>setEditing(null)}>Cancel</Button><Button disabled={saveAll.isPending||!draft.en?.trim()} onClick={()=>saveAll.mutate()}><Save className="mr-2 h-4 w-4"/>{saveAll.isPending?'Saving…':'Save All Translations'}</Button></div></div></div>}
 </div>
}
